### ISSUE TITLE
궁금해요!

### ISSUE THREAD

**Issue by sweun2** [Dcom-KHU/focuz-api-server#21]
![image](https://user-images.githubusercontent.com/46338536/184149886-50318616-1074-4eb3-b216-8c8832f59bf1.png)

user.id의 GenerationType이 IDENTITY면 id값이 null일땐 AUTO처럼 작동하는 것으로 인지하고 있습니다.

![image](https://user-images.githubusercontent.com/46338536/184150270-35b2e0d6-0eb6-4554-8e9c-69fa93f30425.png)

그렇다면 Token값을 통해 user를 찾을 때 이때 id값과 db안에 있는 id값이 다른 것 같아서 email로 찾는 것이 맞는 것 같은데 혹시 제가 잘못
생각하고 있는 부분이 있을까요

![image](https://user-images.githubusercontent.com/46338536/184150875-f6b1bfe4-e773-4862-9fe4-2212942000ac.png)

디코 접속안했길래 여기로 물어봄니다 ㅇㅇ

**Comment by JustKode** [comment]
- GenerationType이 IDENTITY면 기본키 생성을 DBMS의 기본 설정에 위임 합니다. MySQL은 Auto Increment 정책을 기본으로 하고요. 그래서 일단 저 로직에서 유저가 생성 될 때는, 유저가 겹칠일이 없습니다.
- 여기서 token은 OAuth2 token이 아닌, jwt로 userId를 직접 말아준 토큰입니다. JWTFilter를 참고 하세요.
- getUid 함수가 token 내의 User id를 추출 합니다. PK는 기본적으로 indexing을 하기 때문에, UserID를 통해 유저를 찾습니다.

**Comment by sweun2** [comment]
👍👍👍👍👍
